/* eslint-disable no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/laurentiu.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber"

export default function Model(props) {
  const { nodes, materials } = useGLTF('./laurentiu.glb')
  const myMesh = useRef()

  useFrame(({ clock }) => {
    const a = clock.getElapsedTime();
    myMesh.current.position.y = Math.sin(a) * 0.01
  })
  return (
    <group {...props} dispose={null}>
      <mesh ref={myMesh} geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('./laurentiu.glb')
